# Generated by Django 5.2.8 on 2026-02-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_session_id',
        ),
        migrations.AddField(
            model_name='order',
            name='liqpay_order_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='LiqPay Order ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='liqpay_payment_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='LiqPay Payment ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=0, max_length=255, unique=True, verbose_name='Order ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email покупателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание оплаты'), ('paid', 'Оплачено'), ('cancelled', 'Отменено'), ('refunded', 'Возврат'), ('processing', 'В обработке')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
