# Generated by Django 5.2.6 on 2026-05-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_points_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Заробленні бонусні поінти'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_points_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Використані бонусні поінти'),
        ),
    ]
